### PR TITLE
[wip] new architecture implementation

### PR DESCRIPTION
**Pull request by stafyniaksacha**
This PR is the firsts implementation about what we talked in #3

As this changes introduce a lot of breaking changes, I set the base branch on `dev`

I totally rewritten the networking part due to lack of connectivity using the old library

## Status
- [x] Implements `eventEmitter` stytem
- [x] Implements `WebSocket` protocol
- [x] Implements base `query` method
- [x] Implements `offlineMode`
- [x] Implements `queue` system
- [x] Implements base controller injection
- [ ] Implements real-time rooms
- [x] Implements `auth` controller
- [x] Implements `bulk` controller
- [x] Implements `collection` controller
- [x] Implements `document` controller
- [x] Implements `index` controller
- [ ] Implements `realtime` controller
- [x] Implements `server` controller
- [x] Implements `security` controller
- [ ] Implements `memoryStorage` controller
- [ ] Implements tests

## Example

```dart
import 'package:kuzzle/kuzzle_dart.dart';

final kuzzle = Kuzzle(
  WebSocketProtocol('127.0.0.1.xip.io'),
  offlineMode: OfflineMode.auto,
);

void main () async {
  // note that we don't need to await connection to be effective
  kuzzle.connect(); 
  
  final result = await kuzzle.server.info();
  print('[result][server][info] $result');
}
```

### CODE REVIEW

**Comment by prijindal** [comment]
Let me know if you want me to merge this pull request, because as of now realtime, memory storage and tests are the only things left.

Because I think we can use memory storage and tests from the previous code case itself and just keep realtime for a future update

**Comment by stafyniaksacha** [comment]
I have found a bug with auto reconnection that i what to resolve before starting to implement realtime.

The issue is that when a disconnection occurred when were in auto mode, the reconnection happens normally but all error handler are discarded (ie: the next disconnection will not be handled)

**Comment by stafyniaksacha** [comment]
for the tests, IMHO what we need to do in the firsts stages is the tests for protocols

**Comment by stafyniaksacha** [comment]
for the memoryStorage part i was wondering about usage of [`noSuchMethod`](https://www.dartlang.org/articles/language/emulating-functions#interactions-with-mirrors-and-nosuchmethod) but I don't know, it don't allow auto completion

**Comment by prijindal** [comment]
That is alright, those things can be implemented later on

**Pull request merged**
